# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/Ming589/CXLMemSim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/Ming589/CXLMemSim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /users/Ming589/CXLMemSim/CMakeFiles /users/Ming589/CXLMemSim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /users/Ming589/CXLMemSim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CXLMemSim

# Build rule for target.
CXLMemSim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CXLMemSim
.PHONY : CXLMemSim

# fast build rule for target.
CXLMemSim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/build
.PHONY : CXLMemSim/fast

#=============================================================================
# Target rules for targets named CXLMemSimHook

# Build rule for target.
CXLMemSimHook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CXLMemSimHook
.PHONY : CXLMemSimHook

# fast build rule for target.
CXLMemSimHook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimHook.dir/build.make CMakeFiles/CXLMemSimHook.dir/build
.PHONY : CXLMemSimHook/fast

#=============================================================================
# Target rules for targets named CXLMemSimSock

# Build rule for target.
CXLMemSimSock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CXLMemSimSock
.PHONY : CXLMemSimSock

# fast build rule for target.
CXLMemSimSock/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/build
.PHONY : CXLMemSimSock/fast

src/cxlcontroller.o: src/cxlcontroller.cpp.o
.PHONY : src/cxlcontroller.o

# target to build an object file
src/cxlcontroller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/cxlcontroller.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/cxlcontroller.cpp.o
.PHONY : src/cxlcontroller.cpp.o

src/cxlcontroller.i: src/cxlcontroller.cpp.i
.PHONY : src/cxlcontroller.i

# target to preprocess a source file
src/cxlcontroller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/cxlcontroller.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/cxlcontroller.cpp.i
.PHONY : src/cxlcontroller.cpp.i

src/cxlcontroller.s: src/cxlcontroller.cpp.s
.PHONY : src/cxlcontroller.s

# target to generate assembly for a file
src/cxlcontroller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/cxlcontroller.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/cxlcontroller.cpp.s
.PHONY : src/cxlcontroller.cpp.s

src/cxlcounter.o: src/cxlcounter.cpp.o
.PHONY : src/cxlcounter.o

# target to build an object file
src/cxlcounter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/cxlcounter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/cxlcounter.cpp.o
.PHONY : src/cxlcounter.cpp.o

src/cxlcounter.i: src/cxlcounter.cpp.i
.PHONY : src/cxlcounter.i

# target to preprocess a source file
src/cxlcounter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/cxlcounter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/cxlcounter.cpp.i
.PHONY : src/cxlcounter.cpp.i

src/cxlcounter.s: src/cxlcounter.cpp.s
.PHONY : src/cxlcounter.s

# target to generate assembly for a file
src/cxlcounter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/cxlcounter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/cxlcounter.cpp.s
.PHONY : src/cxlcounter.cpp.s

src/cxlendpoint.o: src/cxlendpoint.cpp.o
.PHONY : src/cxlendpoint.o

# target to build an object file
src/cxlendpoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/cxlendpoint.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/cxlendpoint.cpp.o
.PHONY : src/cxlendpoint.cpp.o

src/cxlendpoint.i: src/cxlendpoint.cpp.i
.PHONY : src/cxlendpoint.i

# target to preprocess a source file
src/cxlendpoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/cxlendpoint.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/cxlendpoint.cpp.i
.PHONY : src/cxlendpoint.cpp.i

src/cxlendpoint.s: src/cxlendpoint.cpp.s
.PHONY : src/cxlendpoint.s

# target to generate assembly for a file
src/cxlendpoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/cxlendpoint.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/cxlendpoint.cpp.s
.PHONY : src/cxlendpoint.cpp.s

src/helper.o: src/helper.cpp.o
.PHONY : src/helper.o

# target to build an object file
src/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/helper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/helper.cpp.o
.PHONY : src/helper.cpp.o

src/helper.i: src/helper.cpp.i
.PHONY : src/helper.i

# target to preprocess a source file
src/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/helper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/helper.cpp.i
.PHONY : src/helper.cpp.i

src/helper.s: src/helper.cpp.s
.PHONY : src/helper.s

# target to generate assembly for a file
src/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/helper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/helper.cpp.s
.PHONY : src/helper.cpp.s

src/incore.o: src/incore.cpp.o
.PHONY : src/incore.o

# target to build an object file
src/incore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/incore.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/incore.cpp.o
.PHONY : src/incore.cpp.o

src/incore.i: src/incore.cpp.i
.PHONY : src/incore.i

# target to preprocess a source file
src/incore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/incore.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/incore.cpp.i
.PHONY : src/incore.cpp.i

src/incore.s: src/incore.cpp.s
.PHONY : src/incore.s

# target to generate assembly for a file
src/incore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/incore.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/incore.cpp.s
.PHONY : src/incore.cpp.s

src/logging.o: src/logging.cpp.o
.PHONY : src/logging.o

# target to build an object file
src/logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/logging.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/logging.cpp.o
.PHONY : src/logging.cpp.o

src/logging.i: src/logging.cpp.i
.PHONY : src/logging.i

# target to preprocess a source file
src/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/logging.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/logging.cpp.i
.PHONY : src/logging.cpp.i

src/logging.s: src/logging.cpp.s
.PHONY : src/logging.s

# target to generate assembly for a file
src/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/logging.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/logging.cpp.s
.PHONY : src/logging.cpp.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/module.o: src/module.cc.o
.PHONY : src/module.o

# target to build an object file
src/module.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimHook.dir/build.make CMakeFiles/CXLMemSimHook.dir/src/module.cc.o
.PHONY : src/module.cc.o

src/module.i: src/module.cc.i
.PHONY : src/module.i

# target to preprocess a source file
src/module.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimHook.dir/build.make CMakeFiles/CXLMemSimHook.dir/src/module.cc.i
.PHONY : src/module.cc.i

src/module.s: src/module.cc.s
.PHONY : src/module.s

# target to generate assembly for a file
src/module.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimHook.dir/build.make CMakeFiles/CXLMemSimHook.dir/src/module.cc.s
.PHONY : src/module.cc.s

src/monitor.o: src/monitor.cpp.o
.PHONY : src/monitor.o

# target to build an object file
src/monitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/monitor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/monitor.cpp.o
.PHONY : src/monitor.cpp.o

src/monitor.i: src/monitor.cpp.i
.PHONY : src/monitor.i

# target to preprocess a source file
src/monitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/monitor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/monitor.cpp.i
.PHONY : src/monitor.cpp.i

src/monitor.s: src/monitor.cpp.s
.PHONY : src/monitor.s

# target to generate assembly for a file
src/monitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/monitor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/monitor.cpp.s
.PHONY : src/monitor.cpp.s

src/pebs.o: src/pebs.cpp.o
.PHONY : src/pebs.o

# target to build an object file
src/pebs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/pebs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/pebs.cpp.o
.PHONY : src/pebs.cpp.o

src/pebs.i: src/pebs.cpp.i
.PHONY : src/pebs.i

# target to preprocess a source file
src/pebs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/pebs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/pebs.cpp.i
.PHONY : src/pebs.cpp.i

src/pebs.s: src/pebs.cpp.s
.PHONY : src/pebs.s

# target to generate assembly for a file
src/pebs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/pebs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/pebs.cpp.s
.PHONY : src/pebs.cpp.s

src/perf.o: src/perf.cpp.o
.PHONY : src/perf.o

# target to build an object file
src/perf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/perf.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/perf.cpp.o
.PHONY : src/perf.cpp.o

src/perf.i: src/perf.cpp.i
.PHONY : src/perf.i

# target to preprocess a source file
src/perf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/perf.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/perf.cpp.i
.PHONY : src/perf.cpp.i

src/perf.s: src/perf.cpp.s
.PHONY : src/perf.s

# target to generate assembly for a file
src/perf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/perf.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/perf.cpp.s
.PHONY : src/perf.cpp.s

src/policy.o: src/policy.cpp.o
.PHONY : src/policy.o

# target to build an object file
src/policy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/policy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/policy.cpp.o
.PHONY : src/policy.cpp.o

src/policy.i: src/policy.cpp.i
.PHONY : src/policy.i

# target to preprocess a source file
src/policy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/policy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/policy.cpp.i
.PHONY : src/policy.cpp.i

src/policy.s: src/policy.cpp.s
.PHONY : src/policy.s

# target to generate assembly for a file
src/policy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/policy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/policy.cpp.s
.PHONY : src/policy.cpp.s

src/sock.o: src/sock.cc.o
.PHONY : src/sock.o

# target to build an object file
src/sock.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/sock.cc.o
.PHONY : src/sock.cc.o

src/sock.i: src/sock.cc.i
.PHONY : src/sock.i

# target to preprocess a source file
src/sock.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/sock.cc.i
.PHONY : src/sock.cc.i

src/sock.s: src/sock.cc.s
.PHONY : src/sock.s

# target to generate assembly for a file
src/sock.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/sock.cc.s
.PHONY : src/sock.cc.s

src/uncore.o: src/uncore.cpp.o
.PHONY : src/uncore.o

# target to build an object file
src/uncore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/uncore.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/uncore.cpp.o
.PHONY : src/uncore.cpp.o

src/uncore.i: src/uncore.cpp.i
.PHONY : src/uncore.i

# target to preprocess a source file
src/uncore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/uncore.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/uncore.cpp.i
.PHONY : src/uncore.cpp.i

src/uncore.s: src/uncore.cpp.s
.PHONY : src/uncore.s

# target to generate assembly for a file
src/uncore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSim.dir/build.make CMakeFiles/CXLMemSim.dir/src/uncore.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CXLMemSimSock.dir/build.make CMakeFiles/CXLMemSimSock.dir/src/uncore.cpp.s
.PHONY : src/uncore.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CXLMemSim"
	@echo "... CXLMemSimHook"
	@echo "... CXLMemSimSock"
	@echo "... src/cxlcontroller.o"
	@echo "... src/cxlcontroller.i"
	@echo "... src/cxlcontroller.s"
	@echo "... src/cxlcounter.o"
	@echo "... src/cxlcounter.i"
	@echo "... src/cxlcounter.s"
	@echo "... src/cxlendpoint.o"
	@echo "... src/cxlendpoint.i"
	@echo "... src/cxlendpoint.s"
	@echo "... src/helper.o"
	@echo "... src/helper.i"
	@echo "... src/helper.s"
	@echo "... src/incore.o"
	@echo "... src/incore.i"
	@echo "... src/incore.s"
	@echo "... src/logging.o"
	@echo "... src/logging.i"
	@echo "... src/logging.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/module.o"
	@echo "... src/module.i"
	@echo "... src/module.s"
	@echo "... src/monitor.o"
	@echo "... src/monitor.i"
	@echo "... src/monitor.s"
	@echo "... src/pebs.o"
	@echo "... src/pebs.i"
	@echo "... src/pebs.s"
	@echo "... src/perf.o"
	@echo "... src/perf.i"
	@echo "... src/perf.s"
	@echo "... src/policy.o"
	@echo "... src/policy.i"
	@echo "... src/policy.s"
	@echo "... src/sock.o"
	@echo "... src/sock.i"
	@echo "... src/sock.s"
	@echo "... src/uncore.o"
	@echo "... src/uncore.i"
	@echo "... src/uncore.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

